# Generated by Django 4.1.1 on 2022-09-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(default='', max_length=150, verbose_name='текст задачи')),
                ('deadline', models.DateTimeField(verbose_name='дедлайн')),
                ('task_description', models.TextField()),
            ],
        ),
    ]
